### ISSUE TITLE
PSA: Fix for "ch.njol.skript.SkriptAPIException: No class info found for citizen" error

### ISSUE THREAD

**Issue by BuggyAl** [TheLimeGlass/Skellett#166]
Hello, this is a public service announcement to those that are having issues with Skellet. When getting the ``` ch.njol.skript.SkriptAPIException: No class info found for citizen``` error, follow the steps below to *hopefully* resolve the issue.

1. Make sure you have the latest version of Skellet found at the top of https://github.com/TheLimeGlass/Skellett/releases
2. Install the Citizens plugin from https://ci.citizensnpcs.co/job/Citizens2/ and make sure it is the correct server version
3. Set ```Npc``` in the ```PluginHooks``` section of the Skellet ```plugin.yml``` to "true"

Example "config.yml":
```
PluginHooks:
  LibsDisguises: false
  # If you use Citizens https://www.spigotmc.org/resources/citizens.13811/
  Npc: true
  # If you use CorpseReborn https://www.spigotmc.org/resources/corpsereborn.29875/
  CorpseReborn: false
```
